### ISSUE TITLE
Train dataset of 28K models

### ISSUE THREAD

**Issue by toannguyen1904** [Colin97/PartSLIP#2]
Thanks for your amazing work. The performance of PartSLIP impresses me. Yet I want to ask about the dataset of 28K models that you mentioned in the paper, whose the ```.txt``` file is included in the ```split``` folder of [the dataset repository on HuggingFace](https://huggingface.co/datasets/minghua/PartSLIP/tree/main/). I can not find that and it seems that you have not released this set. It would be super useful if you can release the data to benefit the following research.

**Comment by Colin97** [comment]
Hi, Thanks for your interest. The models in train.txt are not used by PartSLIP. They are only utilized by other baselines for comparison. The models in 'train.txt' are all from PartNet dataset. You can download them [here](https://www.shapenet.org/download/parts).

**Comment by toannguyen1904** [comment]
Thank you very much for your helpful information!

**Comment by toannguyen1904** [comment]
Just wanna investigate more on this interesting work :))
From my understanding, the point clouds of the PartNet dataset do not contain color information. Is this true?
If so, How can PartSLIP handle the point clouds of the PartNet dataset? You assume that the point clouds are dense and colored.

Thanks!

**Comment by Colin97** [comment]
We didn't directly use point clouds of the PartNet dataset. We still render meshes and fuse multi-view images to generate dense point clouds.

The meshes in PartNet dataset are textureless, but the mesh rendering may still contain some shading (as shown in the figure below), which provides color for the points.

In this way, we can get point clouds that are dense and colored (but in gray scale).

<img width="1240" alt="image" src="https://github.com/Colin97/PartSLIP/assets/16759292/4fbd43c2-322e-4bad-98c1-dc6a8c3bfdc8">
(first row: mesh rendering for point cloud generation; second row: point cloud rendering for segmentation)


Note that shapes in `train.txt` are only utilized for baselines in our experiments. But PartSLIP should also be able to handle them if they are captured as mentioned above.

**Comment by toannguyen1904** [comment]
thanks so much!
